var TREE_ITEMS = [
	['CLAB', '/clab2/main.php',
		['Contractor Online', '/clab2/contractor_ol/dashboard.php',
			['Company Registration', '/clab2/contractor_ol/company_reg.php'],
			['Password', '/clab2/contractor_ol/password.php'],
			['Logout', '/clab2/contractor_ol/logout.php'],
		],

			['Contractor', '/clab2/contractor/dashboard.php',
			['Registration', '/clab2/contractor/registration_pt1.php',
			 ['Change Status', '/clab2/contractor/change_status_pt1.php'],
			 ['Assign Labor', '/clab2/contractor/assign_labor_pt1.php'],
			 ],
			['Approval', '/clab2/contractor/approval_pt1.php'],
			['Search', '/clab2/contractor/search_pt1.php'],
			['Reports', '/clab2/contractor/reports_pt1.php'],
		],
		['Labor', '/clab2/labor/dashboard.php',
			['Registration', '/clab2/labor/registration_pt1.php',
			  ['Update Permits', '/clab2/labor/update_permits_pt1.php'],
			  ['Assign Company', '/clab2/labor/assign_company_pt1.php'],
			  ['Change Status', '/clab2/labor/change_status_pt1.php'],
			 ],
			['Search', '/clab2/labor/search_pt1.php'],
			['Reports', '/clab2/labor/reports_pt1.php'],
		],
		['Immigration', '/clab2/immigration/dashboard.php',
			['New Work Order', '/clab2/immigration/new_workorder_pt1.php'],
			['Update Work Order', '/clab2/immigration/update_workorder_pt1.php'],
			['Approval Status', '/clab2/immigration/approval_status.php',
			 ['Internal', '/clab2/immigration/approval_internal_workorder_pt1.php'],
			 ['Immigration', '/clab2/immigration/approval_immigration_workorder_pt1.php'],
			],
		],
		['System Administration', '/clab2/systemadmin/dashboard.php',
			['Add User', '/clab2/systemadmin/add_user.php'],
			['Users List', '/clab2/systemadmin/list_user.php'],
			['Add Group', '/clab2/systemadmin/add_group.php'],
			['Groups List', '/clab2/systemadmin/list_group.php'],
			['Add Entity', '/clab2/systemadmin/add_entity.php'],
			['Entities List', '/clab2/systemadmin/list_entity.php'],
			['Reports', '/clab2/systemadmin/reports.php'],
		],
		['Password', '/clab2/password/password.php',
		 
		],
		['Logout', '/clab2/logout/logout.php',
			
		],
	],
];
