/*
SQLyog Community Edition- MySQL GUI
Host - 5.0.51b-community-nt 
*********************************************************************
Server version : 5.0.51b-community-nt
*/
DELETE FROM employees;
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'admin123','Administration','ADMINISTRATOR','5','1211','121','0','0','1212','0','','0','9014682375','admin','admin');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0010','KHALIZA AZIZ','DATA ENTRY','1','100','03-20959599','0123923144','KHALIZA@CLAB.COM.MY','20959566','0','','PUSAT BANDAR DAMANSARA, KUALA LUMPUR','01237','liza','liza');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0006','SHAARI LISUT','OPERATION EXECUTIVE','1','','03-20959599','0127061780','SHAARI@CLAB.COM.MY','20959566','','','PUSAT BANDAR DAMANSARA, KUALA LUMPUR','0753214','shaari','shaari');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0003','ABD RAZAK MOHD ALI','HEAD OF OPERATIONS','1','106','03-20959599','0192783923','','20959599','','','PUSAT BANDAR DAMANSARA, KUALA LUMPUR','012374','','');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'P0002','HASNOL KAMIL','DATA ENTRY','5','','','','','','','','','023741','hasnol','hasnol');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0007','AZILAH ABDOLAH','OPERATION ASSISTANT','1','112','03-20959599','0173143912','ZILA@CLAB.COM.MY','20959566','','','PUSAT BANDAR DAMANSARA, KUALA LUMPUR','7543210','zila','zila');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'T0001','MUHAMAD REDZUAN ABUDALLAH','IT','5','119','03-20959599','0132306033','redzwan@clab.com.my','20959566','','','PUSAT BANDAR DAMANSARA, KUALA LUMPUR','012345678','redzwan','clab');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0005','FADHLINA MD. LAZIM','SECRETARY','','102','03-20959599','0166065092','FADHLINA@CLAB.COM.MY','20959566','','','PUSAT BANDAR DAMANSARA, KUALA LUMPUR','014','fad','fad');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0001','CAPT AZLAN MOHD ISA','GENERAL MANAGER','','101','03-20959566','0125584636','AZLAN@CLAB.COM.MY','20959566','','','PUSAT BANDAR DAMANSARA, KUALA LUMPUR','7543210','CAPT','010500');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0004','ABD RAFIK BIN ABD RAJIS','HEAD OF FINANCE','2','105','03-20959599','0192733501','RAFIK@CLAB.COM.MY','20959566','','','PUSAT BANDAR DAMANSARA, KUALA LUMPUR','347012','RAFIK','RAFIK');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0008','NORAINI BTE ARIF SHAH','OPERATION ASSISTANT','1','109','20959599','0125701180','NORAINI@CLAB.COM.MY','20959566','','','PUSAT BANDAR DAMANSARA, KUALA LUMPUR','1023457','noraini','141279');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0011','NORMAH BT TALIB','IT','5','116','03-20959599','0132547924','normah@clab.com.my','20959566','','','PUSAT BANDAR DAMANSARA, KUALA LUMPUR','01234678','','');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0002','MOHD ROZAINI AB. RAHMAN','HEAD OF DEPARTMENT & OPERATIONS','3','103','03-20959599','0162163233','rozaini@clab.com.my','20959566','','','PUSAT BANDAR DAMANSARA, KUALA LUMPUR','012347','rozaini','rozaini');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0009','MOHD KHAIRI ABDULLAH','OA','1','120','03-20959599','0129108125','KHAIRI@CLAB.COM.MY','20959566','','','PUSAT BANDAR DAMANSARA, KUALA LUMPUR','012347','khairi','khairi');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'P0001','NATALIA','IT','1','','','','','','','','','01237','','');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0012','MARDZIYAH MOHD SAZILI','FINANCE','2','114','03-20959599','0126613573','MARDY@CLAB.COM.MY','20959566','','','PUSAT BANDAR DAMANSARA, KUALA LUMPUR','0123457','mardy','imation');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0013','WAN MOHD HAFIZAL','OPERATION ASSISTANT','1','','','','hafizal@clab.com.my','','','','','012347','hafizal','hafizal');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0014','FAIZAL','HR EXECUTIVE','3','','','','faizal@clab.com.my','','','','','012347','faizal','faizal');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0015','ROHAIDA MOHAMED SAAD','OPERATION ASSISTANT','1','','','','','','','','','012347','rohaida','rohaida');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0016','NADURA KAMARULZAMAN','OPERATION ANALYSYT','','','','','','','','','','012347','','');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'T0002','ROHAIDAH BT SAPUAN','OPERATION','1','','','','','','','','','012347','ROHAIDAH','ROHAIDAH');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0017','NUR AKRAM BIN MUHAMMAD ZABRI','IT Coodinator','5','','','','','','','','','01234678','akram','akram');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0018','Zam Zarina Mohamad Ishak','Human Resource Executive','3','','','','zam_zarina@clab.com.my','','','','','0147','zam','zam');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0019','Annettee','Operation Assistant','1','','','','annettee@clab.com.my','','','','','012347','annettee','annettee');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0020','Noor Farah Hanim Bt Mohd Suffian','Operation Assistant','1','','','','farah@clab.com.my','','','','','012347','farah','farah');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0021','Muhammad Asyraf Bin Jasni','ICT Administrator','5','','','','asyraf@clab.com.my','','','','','01234678','asyraf','asyraf');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0022','Elisia Shahnaz Sharatol Ahmad Shah','Senior Finance & Admin Assistant','2','','','','elisia_shahnaz@clab.com.my','','','','','01','','');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0023','MOHD FAIZAL B. MOHD SUKI','OPERATION ASSISTANT','1','','','','mohd_faizal@clab.com.my','','','','','012347','mohdfaizal','faizal');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'P0003','SITI NOOR AISHAH BINTI MARKAM','DATA ENTRY','5','','','','','','','','','012347','aishah','aishah');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0024','ERINA AHMAD SUHAIMI','HR ASSISTANT','3','','','','erina@clab.com.my','','','','','01','erina','erina');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0025','JASMIN LIM ABDULLAH','HEAD OF BUSINESS DEV.','','','','','jasmin_lim@clab.com.my','','','','','017','','');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'P0004','IDA FARIHA BINTI MOHD YUSOF','DATA ENTRY','5','','','','ida@clab.com.my','','','','','012347','','');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0026','NORIZAN BINTI MD ZAIN','FINANCE ASSISTANT','2','','','','norizan@clab.com.my','','','','','01','norizan','norizan');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0027','MOHD SHAHRUL NIZAM','ADMIN ASSISTANT','4','','','','shahrul@clab.com.my','','','','','012347','shahrul','shahrul');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0028','RAVINDER KAUR','HEAD OF LEGAL','','','','','ravinder@clab.com.my','','','','','01472','','');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0029','MD. MOHMOOD BIN CHE MID','DEPUTY HEAD OF OPERATIONS','1','','','','mohmod@clab.com.my','','','','','012347','mohmod','mohmod');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0030','ERNIE YOSITA BT HUSSIN','OPERATION ASSISTANT','1','','','','ernie@clab.com.my','','','','','012347','ernie','ernie');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0031','MUHAMMAD HELMY BIN KAMBALI','OPERATION ANALYST','','','','','helmy@clab.com.my','','','','','043217','helmy','helmy');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'P0005','NORAZIAH BINTI ABDUL WAHAB','DATA ENTRY','5','','','','noraziah@clab.com.my','','','','','012347','noraziah','noraziah');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0032','MOHAMED ZAMIR SHAH BIN HAMZAH','OPERATION ASSISTANT','1','','','','zamir@clab.com.my','','','','','012347','zamir','zamir');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0033','MAI NURUN SUHAILA','LEGAL EXECUTIVE','','','','','suhaila@clab.com.my','','','','','012347','suhaila','suhaila');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0034','KHAIRINA IZFA ABDUL HADI','','','','','','khairina.izfa@clab.com.my','','','','','012347','khairina','khairina');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0035','SHAHRIL ANUAR BIN ASSAKRI','ADMIN ASSISTANT','4','','','','shahril.anuar@clab.com.my','','','','','012347','shahril','shahril');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'P0006','SURIANI BINTI NOOR ZAIDY','DATA ENTRY CLERK','5','','','','suriani@clab.com.my','','','','','012347','suriani','suriani');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'P0007','HARNINI BINTI LAJIS','DATA ENTRY CLERK','5','','','','harnini@clab.com.my','','','','','012347','harnini','harnini');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0036','Marliana Anisah Ramli','Customer Service','1','','','','','','','','','01246','marliana','marliana');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0037','NORLIDA BINTI BADERI','CUSTOMER SERVICE','1','','','','','','','','','01246','norlida','norlida');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0038','NURNABILA BINTI MOHD BADRI','ACCOUNT CLERK','2','','','','','','','','','01467','nabila','nabila');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E0039','NORNI SUKRIYATI BINTI MUSTHAR','INTERNAL AUDIT EXECUTIVE','','','','','','','','','','701','norni','norni');
INSERT INTO employees (emp_id, emp_num, emp_name, emp_position, emp_dpt_id, emp_extension, emp_workphone, emp_handphone, emp_email, emp_fax, emp_housephone, emp_address, emp_office_location, emp_accessibility, emp_username, emp_password) VALUES(NULL, 'E035','Saiful Adly Mohamad Khairi','Operation Coordinator','1','209','','','adly@clab.com.my','','','','Pusat Bandar Damansara','743210','adly','adly');
